server:
  port: 8082
spring:
  datasource:
    generate-unique-name: true
  application:
    name: campanha-service
  

eureka: 
  client:
     serviceUrl:
       default: http://localhost:8761/eureka/ 