server:
  port: 8081


campanha:
  ip: http://localhost
  port: 8082

spring:
  datasource:
    generate-unique-name: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: socio-torcedor
    
eureka: 
  client:
     serviceUrl:
       default: http://localhost:8761/eureka/ 


 